language: ruby
rvm:
  - 2.3

before_deploy:
  - bash -c "[ ! -d bonsai/ ] && git clone https://github.com/sensu/sensu-go-bonsai-asset.git bonsai || echo 'bonsai/ exists, skipping git clone'"

deploy:
  - provider: script
    script: bonsai/ruby-runtime/travis-build-ruby-plugin-assets.sh sensu-plugins-ipmi-sensors
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
      rvm: 2.3
